//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlycycybergames.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Kho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kho()
        {
            this.DichVu = new HashSet<DichVu>();
        }

        [Display(Name = "Mã mặt hàng")]
        [Required(ErrorMessage = "Mã mặt hàng không được bỏ trống!")]
        public string ID_Mathang { get; set; }

        [Display(Name = "Tên mặt hàng")]
        [Required(ErrorMessage = "Tên mặt hàng không được bỏ trống!")]
        public string TenMatHang { get; set; }

        [Display(Name = "Số lượng")]
        [Required(ErrorMessage = "Số lượng không được bỏ trống!")]
        public string SoLuong { get; set; }

        [Display(Name = "Tình trạng")]
        [Required(ErrorMessage = "Tình trạng không được bỏ trống!")]
        public string TinhTrang { get; set; }

        [Display(Name = "Ngày nhập hàng")]
        [Required(ErrorMessage = "Ngày nhập hàng không được bỏ trống!")]
        public Nullable<System.DateTime> NgayNhap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DichVu> DichVu { get; set; }
    }
}
