//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlycycybergames.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class May
    {
        [Display(Name = "Mã máy")]
        [Required(ErrorMessage = "Mã máy không được bỏ trống!")]
        public string ID_May { get; set; }

        [Display(Name = "Tên máy")]
        [Required(ErrorMessage = "Tên máy không được bỏ trống!")]
        public string TenMay { get; set; }

        [Display(Name = "Giá máy")]
        [Required(ErrorMessage = "Giá máy không được bỏ trống!")]
        public string GiaMay { get; set; }

        [Display(Name = "Tình trạng hoạt động")]
        [Required(ErrorMessage = "Tình trạng hoạt động không được bỏ trống!")]
        public bool? HoatDong { get; set; }

        [Display(Name = "Thời gian mở máy")]
        [Required(ErrorMessage = "Thời gian mở máy không được bỏ trống!")]
        public Nullable<System.DateTime> ThoiGianMo { get; set; }

        [Display(Name = "Thời gian tắt máy")]
        [Required(ErrorMessage = "Thời gian tắt máy không được bỏ trống!")]
        public Nullable<System.DateTime> ThoiGianTat { get; set; }

        [Display(Name = "Tổng tiền")]
        [Required(ErrorMessage = "Tổng tiền không được bỏ trống!")]
        public Nullable<decimal> TongTien { get; set; }

        [Display(Name = "Mã tài khoản")]
        [Required(ErrorMessage = "Mã tài khoản không được bỏ trống!")]
        public string ID_TaiKhoan { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
