//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlycycybergames.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoan()
        {
            this.May = new HashSet<May>();
        }

        [Display(Name = "Mã tài khoản")]
        [Required(ErrorMessage = "Mã tài khoản không được bỏ trống!")]
        public string ID_TaiKhoan { get; set; }

        [Display(Name = "Tên tài khoản")]
        [Required(ErrorMessage = "Tên tài khoản không được bỏ trống!")]
        public string TenTaiKhoan { get; set; }

        [Display(Name = "Mật khảu")]
        [Required(ErrorMessage = "Mật không được bỏ trống!")]
        public string Matkhau { get; set; }

        [Display(Name = "Thời gian nạp")]
        [Required(ErrorMessage = "Thời gian nạp không được bỏ trống!")]
        public Nullable<System.DateTime> ThoiGianNap { get; set; }

        [Display(Name = "Số tiền nạp")]
        [Required(ErrorMessage = "Số tiền nạp không được bỏ trống!")]
        public Nullable<decimal> SoTienNap { get; set; }

        [Display(Name = "Mã khách hàng")]
        [Required(ErrorMessage = "Mã khách hàng không được bỏ trống!")]
        public string ID_KhachHang { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<May> May { get; set; }
    }
}
